export const LANGUAGE_HINTS: Record<string, string> = {
  '.py': 'python',
  '.pyi': 'python',
  '.pyx': 'cython',
  '.js': 'javascript',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  '.ts': 'typescript',
  '.mts': 'typescript',
  '.cts': 'typescript',
  '.jsx': 'jsx',
  '.tsx': 'tsx',
  '.java': 'java',
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  '.cs': 'csharp',
  '.fs': 'fsharp',
  '.vb': 'vb',
  '.go': 'go',
  '.rs': 'rust',
  '.c': 'c',
  '.h': 'c',
  '.cpp': 'cpp',
  '.cc': 'cpp',
  '.cxx': 'cpp',
  '.hpp': 'cpp',
  '.rb': 'ruby',
  '.php': 'php',
  '.pl': 'perl',
  '.pm': 'perl',
  '.swift': 'swift',
  '.scala': 'scala',
  '.clj': 'clojure',
  '.html': 'html',
  '.htm': 'html',
  '.vue': 'vue',
  '.svelte': 'svelte',
  '.css': 'css',
  '.scss': 'scss',
  '.sass': 'sass',
  '.less': 'less',
  '.json': 'json',
  '.jsonc': 'jsonc',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.toml': 'toml',
  '.xml': 'xml',
  '.xsl': 'xsl',
  '.xslt': 'xslt',
  '.sh': 'bash',
  '.bash': 'bash',
  '.zsh': 'zsh',
  '.fish': 'fish',
  '.ps1': 'powershell',
  '.psm1': 'powershell',
  '.sql': 'sql',
  '.graphql': 'graphql',
  '.gql': 'graphql',
  '.md': 'markdown',
  '.markdown': 'markdown',
  '.rst': 'rst',
  '.dockerfile': 'dockerfile',
  '.tf': 'terraform',
  '.tfvars': 'terraform',
  '.ini': 'ini',
  '.cfg': 'ini',
  '.conf': 'ini',
  '.env': 'dotenv',
  '.env.example': 'dotenv',
  '.r': 'r',
  '.R': 'r',
  '.lua': 'lua',
  '.ex': 'elixir',
  '.exs': 'elixir',
  '.erl': 'erlang',
  '.hrl': 'erlang',
  '.hs': 'haskell',
  '.ml': 'ocaml',
  '.mli': 'ocaml',
  '.nim': 'nim',
  '.zig': 'zig',
  '.v': 'v',
  '.dart': 'dart',
  '.groovy': 'groovy',
};

export const TECH_STACK_MAPPING: Record<string, string[]> = {
  TypeScript: ['.ts', '.tsx'],
  JavaScript: ['.js', '.jsx', '.mjs'],
  Python: ['.py'],
  Go: ['.go'],
  Rust: ['.rs'],
  Java: ['.java'],
  Kotlin: ['.kt', '.kts'],
  'C#': ['.cs'],
  Ruby: ['.rb'],
  PHP: ['.php'],
  Swift: ['.swift'],
  Scala: ['.scala'],
  C: ['.c', '.h'],
  'C++': ['.cpp', '.cc', '.hpp'],
};

export function getLanguage(filename: string, extension: string): string {
  if (filename === 'Dockerfile') return 'dockerfile';
  if (filename === 'Makefile') return 'makefile';
  if (filename.startsWith('.env')) return 'dotenv';
  return LANGUAGE_HINTS[extension.toLowerCase()] ?? '';
}
